### ISSUE TITLE
Creating a requirement file for package needed 

### ISSUE THREAD

**Issue by chyan26** [AstarVienna/METIS_Pipeline#10]
Since there are more dependencies package right now, eg. schema.  We would need to create a requirement file for package checking.

**Comment by hugobuddel** [comment]
Since #48 we have https://github.com/AstarVienna/METIS_Pipeline/blob/main/metisp/pymetis/setup.cfg.in which should contain our dependencies. We are currently not using that file, but that is the idea, so closing this.

We currently don't use schema, as we cannot freely add dependencies.
