### ISSUE TITLE
EDPS workflow directory allows .py files only

### ISSUE THREAD

**Issue by chyan26** [AstarVienna/METIS_Pipeline#51]
A YAML file in EDPS workflow caused EDPS to fail.  We should place this file in another place.

**Comment by hugobuddel** [comment]
That is the official place for the `metis_parameters.yaml`... How does this make the EDPS fail?

**Comment by hugobuddel** [comment]
By the way, I would not have merged #50  if there would have been a github action that would fail. My workflow really benefits from having github actions. Guess I should make one then

**Comment by hugobuddel** [comment]
As discussed on slack, let's just remove the file for now.

I'll put some simple tests in place to prevent breaking the workflow again and then we can take it from there.

**Comment by hugobuddel** [comment]
I deleted the file, my apologies
