### ISSUE TITLE
Establish CI/CD on algorithms without using EDPS server and simulation data

### ISSUE THREAD

**Issue by chyan26** [AstarVienna/METIS_Pipeline#9]
Due to the limitation of simulation data, we should establish the CI/CD on algorithm without using ScopeSim data.

**Comment by hugobuddel** [comment]
Solved in #52 .

We now have small test data in https://github.com/AstarVienna/METIS_Pipeline_Test_Data and use that in the CI.

We can improve on this later, closing this for now. We can make more specific issues like setting up regression tests.
